### PR TITLE
[models] Implemented default password hashers #128

### LINKED ISSUE #128: [bug] Not all password hashers are implemented for radcheck model
Currently only 'Cleartext-Password', 'LM-Password' and 'NT-Password' have been implemented.  Adding an entry to the 'Radius Checks' Admin form with any of the following Attributes;

MD5-Password
SMD5-Password
SSHA-Password
Crypt-Password

Results in the following error;

Exception Type:  UnboundLocalError
Exception Value:  local variable 'password_renewed' referenced before assignment

### PR DESCRIPTION
**Pull request by 2stacks**
I've added code to hash passwords as suggested in http://www.openldap.org/faq/data/cache/347.html. 
There is more than one way to go about this but since the intent is to use django's auth_user table this effort only benefits anyone not using the Rest API for authentication.  None of these password hashing methods should be used.  Freeradius can support more advanced hashing methods as described in https://freeradius.org/radiusd/man/rlm_pap.html. Many of these are OS dependent and compatibility with LDAP may require RFC 2307 style headers.  Perhaps a set of supported use cases can be defined, for using radcheck for authentication instead of or in addition to the auth_user table, so that more secure hashing methods can be implemented.

 Fixes #128

### CODE REVIEW

**Comment by nemesisdesign** [comment]
@peppelinux since you added this feature, could you help out in testing and reviewing this patch?

**Comment by 2stacks** [comment]
For anyone interested in testing, make sure freeradius is only configured with sql (not rest) in the authorize section.  All password hashers were tested using radtest on both debian stretch and alpine linux 3.7.

**Comment by 2stacks** [comment]
Im not sure I understand what you mean.

**Comment by rohithasrk** [comment]
Yes basically. Because this function is going to break if an attribute other than the above ones are specified. Like if I put in a new non password attribute like Max-Session-Limit, it probably doesn't need any encoding or hashing.

**Comment by 2stacks** [comment]
I think we can avoid this by adding more if statements to the model manager?

**Comment by 2stacks** [comment]
In my commit I remove the model field blank=True.  Is there a use case for
this?  I cant think of any entry in the radcheck table that is usable
without an attribute type.

**Comment by rohithasrk** [comment]
I don't think so. But you might have to generate new migration files.

**Comment by 2stacks** [comment]
Agreed, this was committed in #131

**Comment by 2stacks** [comment]
I've added the requested changes.  I think this should merge with #110 now.  We still need to address issue #134. I think the admin form should  keep the existing field restrictions if the attribute is a password. I recommend we differentiate between password and non password attributes.  Also, it doesn't hurt but it's confusing to run non password attributes through the _encode_secret function.

**Comment by 2stacks** [comment]
I rebased this pull request on the recent merge of #110.  Please review and let me know if it is acceptable.

**Comment by 2stacks** [comment]
No problem.  Should I rebase again with latest merges to master?

**Comment by 2stacks** [comment]
Id be more than happy to add documentation.  Let me know if you want it as
part of this PR.  I have a busy week so it may not be before the weekend.

**Comment by 2stacks** [comment]
I'll rebase again.  The #138 merge has conflicts with the tests I added.

**Comment by rohithasrk** [comment]
Yeah @2stacks. Basically, we are reusing the tests in the sample_app and not duplicating. So we'd just need to import them and make sure they work here.

**Comment by 2stacks** [comment]
No problem, I'll rebase and modify my tests to match.

**Comment by rohithasrk** [comment]
Give me 5 more minutes as I'm going to push one more commit to master.

**Comment by 2stacks** [comment]
Im working on some now.  Do you have a preference for page title?  This
feature covers both Authorization and Authentication in Freeradius.

**Comment by nemesisdesign** [comment]
@2stacks "Authorization with Radius Checks"? Anything better in mind?

**Comment by 2stacks** [comment]
Nope, that's along the lines of what I was thinking.

On Tue, Jul 10, 2018 at 10:08 AM, Federico Capoano <notifications@github.com

**Comment by 2stacks** [comment]
Just one more question, should this documentation go on its own page or be
a subsection under "Installation and configuration of Freeradius3" section?

**Pull request merged**
