### PR TITLE
Add other Nas Type

### PR DESCRIPTION
**Pull request by AlessiaVe**
For have two fields in the admin's interface, which aren't in the model, I added a file Forms.py. In this file there is a class NasModelForm with two fields: standard_type and other_NAS_type. For saving the correct value of the type in the model I overrode the method save_model of the class AbstractNasAdmin in admin.py. I made these changes as solution of the issue #59. I did flake8, isort and coverage test.

### CODE REVIEW

**Comment by peppelinux** [comment]
isort fails, I know your feel :)
Once the changments will be done remember to
````
git commet --amend 
````
to join and overwrite the latest two commits into one.

**Comment by peppelinux** [comment]
Mitica. l'hai fatto :)

**Comment by AlessiaVe** [comment]
The documentation? What file I have to change?

**Comment by peppelinux** [comment]
docs/source/
here you'll find all the doc sources.
there's also a shpinx builder for validation (so: flask+isort+cover+sphinx_build)

**Pull request closed without merging**
