### PR TITLE
rad_check.is_active,  also some list_display and list_filter in admin backend

### PR DESCRIPTION
**Pull request by peppelinux**
Hi Federico,

I'm going to implement your very good app into a existing project, I really appreciate the latest Django 1.11 swappable feature you done and also the API controller that promise to me a lot of good flexibility for future implementations.

I'll continue on my project but if there are some other features to face together I'm open to follow your certainly good ideas.

I don't know if my changes into the code could sounds helpfull for your goals, I just want to share as they are and, optionally, discuss them together with you. Best regards

### CODE REVIEW

**Comment by nemesisdesign** [comment]
@peppelinux thx for contributing, the patch looks useful, the build is failing for small style issues, could you fix those? I would fix myself but I will be super busy until 6th of November.

**Comment by peppelinux** [comment]
Yeah, I just face where's those style issues.
Consider it done

**Comment by nemesisdesign** [comment]
You can replicate the issues by installing the `requirements-test.txt` and then running flake8 and isort checks as in the [.travis build](https://github.com/openwisp/django-freeradius/blob/master/.travis.yml#L22-L24)

**Comment by peppelinux** [comment]
I've just saw the travis-ci Details and yes, I have to face those styles issues, they're trivial.
there's no problem at all, I only need some days because I'm a bit busy at this moment but don't worry, that's mine!

**Comment by nemesisdesign** [comment]
@peppelinux ready? If you could also squash the commits into one it would be better otherwise I can do it for you ;-)

**Comment by nemesisdesign** [comment]
@peppelinux I could merge but I noticed the commit has an email mismatch with your github account.
If I merge your account won't show up as a contributor but I'd like to fix this. Can you?

**Comment by peppelinux** [comment]
ohhh, Really sad for all this problems Federico. I've just fixed it, adding my istitutional email in my github settings. I'm very sorry for all this waste of time to you.

**Comment by nemesisdesign** [comment]
@peppelinux no problem at all, it happens, thanks for contributing. We'll soon have news about this project ;-)

**Comment by peppelinux** [comment]
I think that this app is the best BASE app to start deployng freeradius management into Django.

Soon as possibile I'll have to implement a radcheck/eapol_test to let our user administrators to test user accounts directly from admin action. This should be called regarding to the radcheck_password_type (NT-Password-> eapol_test, Cleartext-Password->radcheck), as Feature Request #52 describes.

this feature will let the eduroam operators to test, via web, the credentials without knowing them.
the problem is that eapol_test works hashing a cleartext definition. So, I just have to take the time to face and deploy the right I/O for this.

I think that a subprocess.Popen should be enough for the radcheck/eapol_test exectuion.
Time will let me see :)

**Comment by nemesisdesign** [comment]
@peppelinux thx for the explaination, I think you should copy this text into #52 for completeness

**Pull request merged**
