### PR TITLE
reused tests in sample_radius/tests.py.

### LINKED ISSUE #119: [tests] Are we really reusing base tests in the sample app?
Recently we worked on #83, but checking the tests in the sample app it doesn't seem to me that [the base tests are being imported](https://github.com/openwisp/django-freeradius/blob/1d2f7d8890d331ceb322d561c4a3e3649e6bb9ed/tests/sample_radius/tests.py) and hence I'm not sure the base tests are run in the sample app too.

### PR DESCRIPTION
**Pull request by R9295**
Fixes #119 
Sorry for the resend

### CODE REVIEW

**Comment by R9295** [comment]
Yes

**Comment by R9295** [comment]
Whoops, will do

**Comment by rohithasrk** [comment]
Hey @R9295. Also check out https://coveralls.io/jobs/38181512. I think you are missing out the management commands too.

**Comment by R9295** [comment]
Added the test

**Pull request merged**
